In [140]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [141]:
import numpy as np
arr=np.array(my_list)
arr

array([1, 2, 3])

In [142]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
arr2=np.array(my_mat)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [143]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [145]:
np.zeros(3)

array([0., 0., 0.])

In [146]:
np.zeros((2,3)) #2 rows 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [147]:
np.ones(2)

array([1., 1.])

In [148]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [149]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [150]:
np.eye(5) # creates a identity matrix that is one as diagonal & others as zero

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [151]:
np.random.rand(5)  #numbers between 0 and 1 [Exclusive]  -1D array

array([0.37711185, 0.77761165, 0.87027637, 0.56526839, 0.41480091])

In [152]:
np.random.rand(5,5)

array([[0.56271971, 0.74385276, 0.56195363, 0.09549686, 0.21541333],
       [0.08900503, 0.31263042, 0.35529424, 0.62770582, 0.84587874],
       [0.73460436, 0.40334463, 0.20294652, 0.34773149, 0.79089877],
       [0.95411575, 0.28643436, 0.34691955, 0.03433247, 0.19984965],
       [0.96726963, 0.49793525, 0.08249053, 0.07903911, 0.54992265]])

In [153]:
np.random.randn(2) #to get 2 numbers from standard nrmal distribution  -1D array

array([-0.03791279, -0.36039462])

In [154]:
np.random.randn(2,2) #-2D array

array([[-0.47137324,  0.06177197],
       [-1.25455275,  0.45808204]])

In [155]:
np.random.randint(1,10)

5

In [156]:
np.random.randint(1,10,5) #5 random numbers from 1-10

array([4, 3, 5, 5, 6], dtype=int32)

In [157]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [158]:
arr=arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [159]:
arr.reshape(5,3)

ValueError: cannot reshape array of size 25 into shape (5,3)

In [160]:
arr.ndim

2

In [161]:
arr.max() #to get maximum value in array

np.int64(24)

In [162]:
arr.min() #to get minimum value in array

np.int64(0)

In [163]:
arr.argmax() #argmax()  converts it into a 1D list and finds the index of the maximum value--by default

np.int64(24)

In [164]:
arr.argmin()

np.int64(0)

In [165]:
a=[1,2,3,4]
b=["Chaitresh","Varun","Shivaprasad","Nagatejas"]
arr=np.column_stack((a,b))
arr

array([['1', 'Chaitresh'],
       ['2', 'Varun'],
       ['3', 'Shivaprasad'],
       ['4', 'Nagatejas']], dtype='<U21')

In [166]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [167]:
print(arr[3])

4


In [168]:
print(arr[1:3])

[2 3]


In [169]:
arr=np.arange(1,11)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [170]:
arr[0:5]=100
print(arr)  #In normal list we cant do this

[100 100 100 100 100   6   7   8   9  10]


In [171]:
copy=arr[0:6]
copy

array([100, 100, 100, 100, 100,   6])

In [172]:
copy[0:]=50
print(copy)
print(arr)   #Data is not copied its just a view



[50 50 50 50 50 50]
[50 50 50 50 50 50  7  8  9 10]


In [173]:
#If you dont want viw and want a copy of it then we should use variable.copy()
b=arr.copy()
b

array([50, 50, 50, 50, 50, 50,  7,  8,  9, 10])

In [174]:
b[0:6]=100
print(b)


print(arr)

[100 100 100 100 100 100   7   8   9  10]
[50 50 50 50 50 50  7  8  9 10]


In [175]:
arr=np.arange(0,25)
arr=arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [176]:
arr[3]

array([15, 16, 17, 18, 19])

In [177]:
arr[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [178]:
arr[:2,1:]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [179]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [180]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [181]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [182]:
arr=np.arange(1,11)
print(arr)
arr2=np.arange(11,21)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [183]:
add=np.add(arr,arr2)
a

[1, 2, 3, 4]

In [184]:
sub=np.subtract(arr,arr2)
sub

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [185]:
mul=np.multiply(arr,arr2) #---For 1D array
mul

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [186]:
arr1=np.arange(0,25)
arr1=arr1.reshape(5,5)
print(arr1)
print(arr1.dot(arr1)) #Multiplication for 2D matrix

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 150  160  170  180  190]
 [ 400  435  470  505  540]
 [ 650  710  770  830  890]
 [ 900  985 1070 1155 1240]
 [1150 1260 1370 1480 1590]]


In [187]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [188]:
print(arr/0)

[inf inf inf inf inf inf inf inf inf inf]


C:\Users\user\AppData\Local\Temp\ipykernel_14056\1395739493.py:1: RuntimeWarning: divide by zero encountered in divide
  print(arr/0)


In [189]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [191]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])